# doc: https://openethereum.github.io/Configuring-OpenEthereum.html#config-file

[parity]
base_path = "data"
chain = "spec.json"

[network]
# don't attempts to connect to non-public IPs (hosters do not like that)
allow_ips = "public"

[mining]
min_gas_price = 1000000000

[misc]
# If run as systemd service, journald will persist log output.
# Uncomment the following line in order have OpenEthereum log to a file itself.
#log_file = "openethereum.log"

